name: phoenix_socket_example
description: Flutter chat app example for phoenix_socket

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  phoenix_socket:
    path: ../
